# Use an official Python runtime as a parent image
FROM python:3.11-bullseye

# Set the working directory to /app
WORKDIR /app

# Install deps
COPY pyproject.toml ./
RUN pip install .[dev]
RUN pip install .[tests]

# Setup dev env
COPY makefile pyproject.toml ./
RUN make type-check

COPY .pre-commit-config.yaml ./
RUN git init && make lint

RUN type -p curl >/dev/null || (apt update && apt install curl -y) && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \ 
    && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update \
    && apt install gh -y

# Install the entire app
COPY . /app
RUN pip install -e .
