name: Cruft Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cruft-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Cruft
        run: pip install cruft

      - name: Run Cruft Check
        run: |
          if cruft check; then
            echo "Cruft check passed"
          else
            echo "Cruft check failed"
            echo "export CRUFT_FAILED=1" >> $GITHUB_ENV
            exit 0
          fi
      - uses: mshick/add-pr-comment@v2
        if: env.cruft_failed == '1'
        with:
          message: |
            Cruft check failed. Feel free to either disregard or, if you're feeling extra helpful, run `cruft update` and merge in the updates.
