name: Cruft Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cruft-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Cruft
        run: pip install cruft

      - name: Run Cruft Check
        id: cruft_check
        run: |
          if cruft check; then
            echo "Cruft check passed"
            echo "::set-output name=cruft_failed::0"
          else
            echo "Cruft check failed"
            echo "::set-output name=cruft_failed::1"
            exit 1
          fi
      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.cruft_check.outputs.cruft_failed }} == '1'
        with:
          message: |
            Cruft check failed. Feel free to either disregard or, if you're feeling extra helpful, run `cruft update` and merge in the updates.
