# This workflow will install Python dependencies, run pytests and run notebooks
# then it will in python 3.9 (ubuntu-latest) create a badge with the coverage
# and add it to the PR. This badge will be updated if the PR is updated.

name: docker-integration-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    permissions: write-all
    concurrency:
      group: "${{ github.workflow }} @ ${{ github.ref }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: MartinBernstorff
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run integration test
        shell: bash
        run: |
          chmod +x ./tests/integration_test.sh
          ./tests/integration_test.sh